# Generated by Django 4.2.7 on 2023-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount_amount'),
        ),
        migrations.AddField(
            model_name='discount',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discount_amount'),
        ),
    ]
