# Generated by Django 4.2.7 on 2023-12-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_discount_amount_discount_amount_off_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discount_percentage'),
        ),
    ]
