# Generated by Django 4.2.7 on 2023-11-29 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='total_price')),
                ('payment_status', models.CharField(choices=[('in_progress', 'In_Progress'), ('paid', 'Paid')], default='in_progress', max_length=12, verbose_name='payment_status')),
                ('discounts', models.ManyToManyField(related_name='orders', to='pricing.discount', verbose_name='order_discount')),
                ('items', models.ManyToManyField(related_name='orders', to='item.item', verbose_name='order_items')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pricing.tax', verbose_name='order_tax')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
